#!/bin/sh

PID="net.vertigostudios.ledmanager"

if [ -z "$IPKG_OFFLINE_ROOT" ]; then
  IPKG_OFFLINE_ROOT=/media/cryptofs/apps
fi

# Install the java dbus service
rm -f /usr/lib/luna/java/${PID}.jar
cp $IPKG_OFFLINE_ROOT/usr/lib/luna/java/${PID}.jar /usr/lib/luna/java/${PID}.jar
rm -f /usr/share/dbus-1/system-services/${PID}.service
cp $IPKG_OFFLINE_ROOT/usr/share/dbus-1/system-services/${PID}.service /usr/share/dbus-1/system-services/${PID}.service

# Install the upstart script
rm -f /etc/event.d/${PID}
cp $IPKG_OFFLINE_ROOT/etc/event.d/${PID} /etc/event.d/${PID}

exit 0
